addons:
  sonarcloud:
    organization: "azak-azkaran-github" # the key of the org you chose at step #3
env:
    global:
        secure: "k/J8NPzdpa1H4crv/18iOEURKQBhRk9ztfj+fzw6IKIAH7S6nnyKyDN65IGU6ppJc85bj3kC1YQWu7j43oPOWMhG39hRTdNC6IydPb1NEQv53ls4Q50ORodlE01/vN8Po90Vi7L0TiAtsdoIOFpiPemgSMyOGYBMUs9at5S/jngUuppqPiM2GBiaj8/3NQMNIHu3v/VQ4Do8ppYQRWCJoh11BIEx6undYMDkBbjQo6MuGQNAHlKmewLxWkIdAGh9etbMCIo5JAyeA06BkHIdzMFRJcwsFwcd5CY5yznKbjQomzsE/UOUPGzZwbLbDO55SSRNpR0p+g4gMj7wjNXyG1zhnpXfg3l4cq2r9fjW3uE57oiNFDpgLFO7u/zfcQ3YobI9qnBdC80xJxlYzsSRp1Ptn4MgzSdb5wNlUFo1DYlNKNrahHCDTygCoSLJHArNjU32sE5bPMD7/Tja40+8484O64w+J7sosNgP5Wh55S+/etn4vsx9hT8ZjhEDl9gQWgsDSFdy3dY/zZ6moM61UgOwDploS72UGU3DE1B/UBgT/25gX/cqtZdCfv3RipWzwNNTJkncuSJbrqayBdPrYfOpBnT0BCuCI6BSYT2qn6uc8+G/RNb/vf0Ghnd3ny1GIWMcqyIpFktqjw4g4Y3OAcVBioOzMrX6BgcFZY+s3EA="

language: go
sudo: false
go:
  - tip
before_install:
  - sudo apt-get update
script:
  # main folder
  - go test -coverprofile=cover.out
  - go test -json > report.json
  # downloader folder
  - go test github.com/azak-azkaran/putio-go-aria2/aria2downloader/ -coverprofile=./aria2downloader/cover.out
  - go test github.com/azak-azkaran/putio-go-aria2/aria2downloader/ -json > ./aria2downloader/report.json
  # organizer folder
  - go test github.com/azak-azkaran/putio-go-aria2/organize/ -coverprofile=./organize/cover.out
  - go test github.com/azak-azkaran/putio-go-aria2/organize/ -json > ./organize/report.json
  # utils folder
  - go test github.com/azak-azkaran/putio-go-aria2/utils/ -coverprofile=./utils/cover.out
  - go test github.com/azak-azkaran/putio-go-aria2/utils/ -json > ./utils/report.json
  # other script steps might be done before running the actual analysis
  - sonar-scanner
